# Generated by Django 4.2.11 on 2024-04-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
