# Generated by Django 4.2.11 on 2024-03-20 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published'), (2, 'Flagged for Revision')], default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('appetizer', 'Appetizer'), ('main_course', 'Main Course'), ('soup', 'Soup'), ('sides', 'Sides'), ('dessert', 'Dessert')], max_length=30),
        ),
    ]
