# Generated by Django 4.2.11 on 2024-03-28 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_reciperating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reciperating',
            name='average',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='count',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='reciperating',
            name='total',
        ),
    ]
