# Generated by Django 4.2.11 on 2024-04-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_image',
            field=models.BooleanField(default=False),
        ),
    ]
