# Generated by Django 4.2.11 on 2024-04-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_userprofile_has_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_image',
        ),
    ]
